id: P007010
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017093
  title: པདྨ་གླིང་པའི་གཏེར་སྐོར
  author: ''
  volumes:
    008a5c88d21b46198cde152cb0e9a4d5:
      image_group_id: I00EGS1017095
      title: ''
      volume_number: 1
      total_pages: 770
    2a2b117c5bb0497c8331663baa1813d7:
      image_group_id: I00EGS1017096
      title: ''
      volume_number: 2
      total_pages: 444
    92218f3ea95941628388ecb9755e8496:
      image_group_id: I00EGS1017097
      title: ''
      volume_number: 3
      total_pages: 560
    bece4db2533341dfae05b612cc161b0d:
      image_group_id: I00EGS1017098
      title: ''
      volume_number: 4
      total_pages: 548
    ae65059ab1a34b21884ea8d1501a3739:
      image_group_id: I00EGS1017099
      title: ''
      volume_number: 5
      total_pages: 522
    6e519795c5c3468680cef2eb53a9dd76:
      image_group_id: I00EGS1017100
      title: ''
      volume_number: 6
      total_pages: 516
    ecd130c24f7241f0b2f92c41a4d03a28:
      image_group_id: I00EGS1017101
      title: ''
      volume_number: 7
      total_pages: 468
ebook_metadata:
  title: པདྨ་གླིང་པའི་གཏེར་སྐོར
  author: ''
  sku: P007010
  cover: cover.jpg
  layers:
  - pagination
