id: I0CE3BE31
legacy_id: P007010
ocr_import_info:
  bdrc_scan_id: W00EGS1017093
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:24:26'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:08:19.818032+00:00'
last_modified: 2022-08-30 22:13:11.166882
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1017093
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1017093
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: པདྨ་གླིང་པའི་གཏེར་སྐོར།
  author: པདྨ་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.5844940221746726
  ocr_word_median_confidence_index: 0.6000000238418579
quality: null
bases:
  I00EGS1017098:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017098
      total_pages: 548
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00EGS1017098.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5076511851861601
    legacy_id: v004
  I00EGS1017100:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017100
      total_pages: 516
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I00EGS1017100.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.48031139718945337
    legacy_id: v006
  I00EGS1017095:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017095
      total_pages: 770
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017095.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6297806422411167
    legacy_id: v001
  I00EGS1017096:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017096
      total_pages: 444
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00EGS1017096.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6466815338827082
    legacy_id: v002
  I00EGS1017101:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017101
      total_pages: 468
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I00EGS1017101.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.521527510345431
    legacy_id: v007
  I00EGS1017097:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017097
      total_pages: 560
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00EGS1017097.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6822626778231358
    legacy_id: v003
  I00EGS1017099:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017099
      total_pages: 522
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00EGS1017099.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.5867979791325811
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
