id: I0CE3BE31
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:27:38+00:00'
last_modified: '2022-06-08T11:57:20.896347+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017093
  title: པདྨ་གླིང་པའི་གཏེར་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A95A:
      image_group_id: I00EGS1017095
      title: Volume 1 of pad+ma gling pa'i gter skor
      total_pages: 770
      order: 1
      base_file: A95A.txt
    CBE6:
      image_group_id: I00EGS1017096
      title: Volume 2 of pad+ma gling pa'i gter skor
      total_pages: 444
      order: 2
      base_file: CBE6.txt
    E3EC:
      image_group_id: I00EGS1017097
      title: Volume 3 of pad+ma gling pa'i gter skor
      total_pages: 560
      order: 3
      base_file: E3EC.txt
    CA4B:
      image_group_id: I00EGS1017098
      title: Volume 4 of pad+ma gling pa'i gter skor
      total_pages: 548
      order: 4
      base_file: CA4B.txt
    9FE4:
      image_group_id: I00EGS1017099
      title: Volume 5 of pad+ma gling pa'i gter skor
      total_pages: 522
      order: 5
      base_file: 9FE4.txt
    48F1:
      image_group_id: I00EGS1017100
      title: Volume 6 of pad+ma gling pa'i gter skor
      total_pages: 516
      order: 6
      base_file: 48F1.txt
    86C6:
      image_group_id: I00EGS1017101
      title: Volume 7 of pad+ma gling pa'i gter skor
      total_pages: 468
      order: 7
      base_file: 86C6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
